# Known issues:
# Hive LLAP will not start on small machines
# NiFi moved to 9092 to avoid a port clash when everything is on one node

desc: Single node cluster including HDP-3.0.1 & HDF-3.3
deploywait: 1800
purge: true
priority: 
seq:
- copy_def: [inf-hdp30-single, cda30-s]
- merge_def: [inf-cda30-single, cda30-s]
- prep_deps: [cda30-s, cda30-s]
- prep_spec: [cda30-s, cda30-s]
- do_builds: [cda30-s]
- open_port: [tcp, 8080, 8080, '0.0.0.0/0']
input:
  yarn.vcores: 12
  yarn.capacity: 28672
  enable_hive_interactive: false
  fs.s3a.access.key: GET:config.profile.platform.key
  fs.s3a.secret.key: GET:config.profile.platform.secret
blueprint:
  name: blueprint.json
group:
  master:
    machine: 4x28-8x32
mpack:
- name: hdf330
  desc: HDF 3.3.0
  url: http://public-repo-1.hortonworks.com/HDF/centos7/3.x/updates/3.3.0.0/tars/hdf_ambari_mp/hdf-ambari-mpack-3.3.0.0-165.tar.gz
  purge_on_install: false