desc: Single node cluster with minimal install of HDP-3.0 
purge: true 
deploywait: 1800
seq:
- prep_deps: [inf-hdp30-single, hdp30-s]
- prep_spec: [inf-hdp30-single, hdp30-s] 
- do_builds: [hdp30-s]
- open_port: [tcp, 8080, 8080, '0.0.0.0/0']
blueprint:
  name: blueprint.json
recipe:
- name: remount-tmpfs.sh
  typ: PRE_AMBARI_START
- name: pre-ambari-configs.sh
  typ: PRE_AMBARI_START
group:
  master:
    recipe: [remount-tmpfs, pre-ambari-configs]
    type: GATEWAY
    machine: 4x14-4x16