desc: Multi node cluster including all HCP-1.6 components in independently scalable groups
seq:
- prep_deps: [inf-hcp16-multi, hcp16-m]
- prep_spec: [inf-hcp16-multi, hcp16-m]
- do_builds: [hcp16-m]
- wait_event: [inf-hcp16-multi, hcp16-m, event_type, BILLING_STARTED]
- open_port: [tcp, 8080, 8080, '0.0.0.0/0']
deploywait: 1800
purge: true
input:
  nifi.security.encrypt.configuration.password: CALL:security.generate_password
  nifi.sensitive.props.key: CALL:security.generate_passphrase
  nifi.toolkit.tls.token: CALL:security.generate_passphrase
  nifi.registry.security.encrypt.configuration.password: CALL:security.generate_password
  nifi.registry.sensitive.props.key: CALL:security.generate_passphrase
  ranger.kms.password: CALL:security.generate_password
blueprint:
  name: blueprint.json
recipe:
- name: mysql-client.sh
  typ: PRE_AMBARI_START
- name: metron-db-setup.sh
  typ: POST_AMBARI_START
- name: nodejs.sh
  typ: PRE_AMBARI_START
- name: requests-upgrade.sh
  typ: PRE_AMBARI_START
- name: allow-renewable.sh
  typ: POST_AMBARI_START
- name: noexec-tmp.sh
  typ: PRE_AMBARI_START
group:
  master2:
    recipe: [noexec-tmp]
    type: CORE
    machine: 4x28-8x32
    nodes: 1
  master1:
    recipe: [noexec-tmp]
    type: CORE
    machine: 4x28-8x32
    nodes: 1
  solr:
    recipe: [noexec-tmp]
    type: CORE
    machine: 4x14-4x16
    nodes: 1
  ambari:
    recipe: [noexec-tmp, metron-db-setup, mysql-client, requests-upgrade, allow-renewable]
    type: GATEWAY
    machine: 4x28-8x32
    nodes: 1
  worker:
    recipe: [noexec-tmp]
    type: CORE
    machine: 4x14-4x16
    nodes: 1
  metron:
    recipe: [noexec-tmp, nodejs, requests-upgrade, mysql-client]
    type: CORE
    machine: 4x14-4x16
    nodes: 1
  hbase:
    recipe: [noexec-tmp]
    type: CORE
    machine: 4x14-4x16
    nodes: 1
  kafka:
    recipe: [noexec-tmp]
    type: CORE
    machine: 4x28-8x32
    nodes: 1
  streaming:
    recipe: [noexec-tmp]
    type: CORE
    machine: 4x14-4x16
    nodes: 1
  zookeeper:
    recipe: [noexec-tmp]
    type: CORE
    machine: 4x28-8x32
    nodes: 1
  master3:
    recipe: [noexec-tmp]
    type: CORE
    machine: 4x28-8x32
    nodes: 1
  nifi:
    recipe: [noexec-tmp]
    type: CORE
    machine: 4x14-4x16
    nodes: 1
mpack:
- name: hdp-search
  desc: HDP Search 3.0.0
  url: http://public-repo-1.hortonworks.com/HDP-SOLR/hdp-solr-ambari-mp/solr-service-mpack-3.0.0.tar.gz
  purge_on_install: false
- name: hcp-160
  desc: HCP 1.6.0
  url: http://public-repo-1.hortonworks.com/HCP/centos6/1.x/updates/1.6.0.0/tars/metron/hcp-ambari-mpack-1.6.0.0-7.tar.gz
  purge_on_install: false
- name: hdf-312
  desc: HDF 3.1.2
  url: http://public-repo-1.hortonworks.com/HDF/centos7/3.x/updates/3.1.2.0/tars/hdf_ambari_mp/hdf-ambari-mpack-3.1.2.0-7.tar.gz
  purge_on_install: false
krb:
  mode: test
