desc: Single node cluster with minimal install of HDP-3.0 
purge: true 
deploywait: 1800
seq:
- prep_deps: [inf-hdp30-single, hdp30-s]
- prep_spec: [inf-hdp30-single, hdp30-s] 
- do_builds: [hdp30-s]
- open_port: [tcp, 8080, 8080, '0.0.0.0/0']
infra:
  ambarirepo:
    version: 2.7.1.0
    baseUrl: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.7.1.0
    gpgKeyUrl: http://public-repo-1.hortonworks.com/ambari/centos7/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins
  stackrepo:
    ver: 3.0.1.0-187
    url: http://public-repo-1.hortonworks.com/HDP/centos7/3.x/updates/3.0.1.0/HDP-3.0.1.0-187.xml
blueprint:
  name: blueprint.json
recipe:
- name: remount-tmpfs.sh
  typ: PRE_AMBARI_START
- name: prepare-metastores-30.sh
  typ: PRE_AMBARI_START
- name: phoenix-client.sh
  typ: PRE_AMBARI_START
group:
  master:
    recipe: [remount-tmpfs, prepare-metastores-30, phoenix-client]
    type: GATEWAY
    machine: 4x14-4x16
    nodes: 1