# Known issues:
# Hive LLAP will not start on small machines
# NiFi moved to 9092 to avoid a port clash when everything is on one node

deploywait: 1800
purge: true
priority: 
seq:
- prep_deps: [cda301-compact, cda301-c]
- prep_spec: [cda301-compact, cda301-c]
- do_builds: [cda301-c]
- wait_event: [cda301-compact, cda301-c, event_type, BILLING_STARTED]
- open_port: [tcp, 8080, 8080, '0.0.0.0/0']
input:
  yarn.vcores: 6
  yarn.capacity: 24568
  yarn.max.container: 24385
  fs.s3a.access.key: GET:config.profile.platform.key
  fs.s3a.secret.key: GET:config.profile.platform.secret
infra:
  disktypes: [gp2, standard]
  os: redhat7
  ambarirepo:
    version: 2.7.1.0
    baseUrl: http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.7.1.0
    gpgKeyUrl: http://public-repo-1.hortonworks.com/ambari/centos7/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins
  stackrepo:
    ver: 3.0.1.0-187
    url: http://public-repo-1.hortonworks.com/HDP/centos7/3.x/updates/3.0.1.0/HDP-3.0.1.0-187.xml
blueprint:
  name: blueprint.json
recipe:
- name: pre-ambari-start.sh
  typ: PRE_AMBARI_START
group:
- name: master
  recipe: [pre-ambari-start]
  type: GATEWAY
  machine: m5.2xlarge
  nodes: 1
mpack:
- name: hdf320
  desc: HDF 3.2.0
  url: http://public-repo-1.hortonworks.com/HDF/centos7/3.x/updates/3.2.0.0/tars/hdf_ambari_mp/hdf-ambari-mpack-3.2.0.0-520.tar.gz
  purge_on_install: false