# Known issues:
# Hive LLAP will not start on small machines
# NiFi moved to 9092 to avoid a port clash when everything is on one node

desc: Single node cluster including HDP-3.1 & HDF-3.3
deploywait: 1800
purge: true
priority: 
seq:
- prep_deps: [hdp31-s, hdp31-s]
- prep_spec: [hdp31-s, hdp31-s]
- do_builds: [hdp31-s]
- open_port: [tcp, 8080, 8080, '0.0.0.0/0']
input:
  yarn.vcores: 12
  yarn.capacity: 28672
  enable_hive_interactive: false
blueprint:
  name: blueprint.json
group:
  master:
    machine: 4x28-8x32
    recipe: [pre-ambari-configs]
    type: GATEWAY
recipe:
- name: pre-ambari-configs.sh
  typ: PRE_AMBARI_START